---
- name: Patching Playbook
  hosts: all
  become: true
  tasks:
   - name: Performing the pre-check operations.
     script: /home/john/precheck.sh
     args:
     creates: /home/john/precheck.sh

   - name: Applying all the available patches.
     dnf:
     name: "*"
     state: latest

   - name: Rebooting the machines.
     reboot:
     reboot_timeout: 6000

   - name: Performing the post-check operations.
     script: /home/john/postcheck.sh
     args:
     creates: /home/john/postcheck.sh

   - name: Finding the pre & post check result files.
     shell: (cd /home/john; find . -maxdepth 1 -type f -iname "*.txt") | cut -d'/' -f2
     register: files_to_fetch

   - name: Fetching the result files.
     fetch:
     src: /home/john/{{ item }}
     dest: /home/john
     with_items: "{{ files_to_fetch.stdout_lines }}"
...
